Vagrant.configure("2") do |config|
    # Configurar la VM con Ubuntu
    config.vm.box = "ubuntu/bionic64"
  
    # Asignar memoria RAM y CPU
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
  
    # Configurar la red
    config.vm.network "private_network", type: "dhcp"
  
    # Compartir la carpeta local con el servidor Apache
    config.vm.synced_folder ".", "/var/www/html", owner: "www-data", group: "www-data"
  
    # Provisión para instalar Apache
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y apache2
      sudo systemctl enable apache2
      sudo systemctl start apache2
    SHELL
  end
  